# Generated by Django 5.1.15 on 2026-07-25 10:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestPrepCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='Overrides the <title> tag. Falls back to the page title if left blank. Aim for under 60 characters.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Search-result snippet. Aim for 120-160 characters.', max_length=160)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='trainings/')),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('duration', models.CharField(blank=True, help_text="e.g. '6 weeks, 3 classes/week'", max_length=100)),
                ('fee', models.CharField(blank=True, help_text="e.g. 'BDT 8,000'", max_length=100)),
                ('schedule_info', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Test Prep Course',
                'ordering': ['order', 'title'],
            },
        ),
    ]
