from django.test import TestCase
from django.urls import reverse

from .models import Category, Post


class PostModelTests(TestCase):
    def test_slug_autogenerated_from_title(self):
        post = Post.objects.create(title="Study in Denmark", body="<p>Body</p>")
        self.assertEqual(post.slug, "study-in-denmark")

    def test_slug_uniqueness_appends_suffix(self):
        Post.objects.create(title="Study in Denmark", body="<p>1</p>")
        second = Post.objects.create(title="Study in Denmark", body="<p>2</p>")
        self.assertEqual(second.slug, "study-in-denmark-2")


class PostViewTests(TestCase):
    def setUp(self):
        self.category = Category.objects.create(name="News")
        self.published = Post.objects.create(
            title="Published Post", body="<p>Visible</p>", category=self.category, is_published=True
        )
        self.draft = Post.objects.create(title="Draft Post", body="<p>Hidden</p>", is_published=False)

    def test_list_view_only_shows_published_posts(self):
        response = self.client.get(reverse("blog:list"))
        self.assertContains(response, "Published Post")
        self.assertNotContains(response, "Draft Post")

    def test_category_filter(self):
        response = self.client.get(reverse("blog:category", kwargs={"slug": self.category.slug}))
        self.assertContains(response, "Published Post")

    def test_draft_post_detail_returns_404(self):
        response = self.client.get(reverse("blog:detail", kwargs={"slug": self.draft.slug}))
        self.assertEqual(response.status_code, 404)

    def test_published_post_detail_returns_200(self):
        response = self.client.get(reverse("blog:detail", kwargs={"slug": self.published.slug}))
        self.assertEqual(response.status_code, 200)
