from django.test import TestCase
from django.urls import reverse

from .models import Service


class ServiceModelTests(TestCase):
    def test_slug_autogenerated_from_title(self):
        service = Service.objects.create(
            title="Student Visa Support",
            short_description="Visa help.",
            body="<p>Body</p>",
        )
        self.assertEqual(service.slug, "student-visa-support")

    def test_get_absolute_url(self):
        service = Service.objects.create(title="Bank Support", short_description="x", body="<p>x</p>")
        self.assertEqual(service.get_absolute_url(), f"/services/{service.slug}/")


class ServiceViewTests(TestCase):
    def setUp(self):
        self.service = Service.objects.create(
            title="Application and Admission Support",
            short_description="We handle applications.",
            body="<p>Full details.</p>",
        )

    def test_list_view_returns_200_and_lists_service(self):
        response = self.client.get(reverse("services:list"))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, self.service.title)

    def test_detail_view_returns_200(self):
        response = self.client.get(self.service.get_absolute_url())
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Full details.")

    def test_detail_view_404_for_unknown_slug(self):
        response = self.client.get(reverse("services:detail", kwargs={"slug": "does-not-exist"}))
        self.assertEqual(response.status_code, 404)
