# Generated by Django 5.1.15 on 2026-07-25 10:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='Overrides the <title> tag. Falls back to the page title if left blank. Aim for under 60 characters.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Search-result snippet. Aim for 120-160 characters.', max_length=160)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('icon', models.CharField(blank=True, help_text="Short icon label used by the card icon, e.g. 'visa', 'passport', 'bank', 'plane'.", max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('short_description', models.CharField(max_length=255)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('is_featured', models.BooleanField(default=False, help_text='Featured services appear on the homepage.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
