from django.test import TestCase
from django.urls import reverse

from .models import Country, University


class CountryModelTests(TestCase):
    def test_slug_autogenerated_from_name(self):
        country = Country.objects.create(name="United Kingdom")
        self.assertEqual(country.slug, "united-kingdom")

    def test_university_str_includes_country(self):
        country = Country.objects.create(name="Italy")
        uni = University.objects.create(country=country, name="University of Bologna")
        self.assertIn("Italy", str(uni))


class CountryViewTests(TestCase):
    def setUp(self):
        self.denmark = Country.objects.create(name="Denmark", intake_seasons="February, September")
        self.malaysia = Country.objects.create(name="Malaysia")
        University.objects.create(country=self.denmark, name="University of Copenhagen")

    def test_list_view_returns_all_countries(self):
        response = self.client.get(reverse("destinations:list"))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Denmark")
        self.assertContains(response, "Malaysia")

    def test_list_view_filters_by_search_query(self):
        response = self.client.get(reverse("destinations:list"), {"q": "Den"})
        self.assertContains(response, "Denmark")
        self.assertNotContains(response, "Malaysia")

    def test_detail_view_shows_universities(self):
        response = self.client.get(self.denmark.get_absolute_url())
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "University of Copenhagen")
