# Generated by Django 5.1.15 on 2026-07-25 10:20

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ Category',
                'verbose_name_plural': 'FAQ Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='Overrides the <title> tag. Falls back to the page title if left blank. Aim for under 60 characters.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Search-result snippet. Aim for 120-160 characters.', max_length=160)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(default='Dhaka, Bangladesh', max_length=100)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('internship', 'Internship'), ('contract', 'Contract')], default='full_time', max_length=20)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('is_active', models.BooleanField(default=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, help_text="Emoji or short icon label, e.g. 'search', 'file', 'visa', 'plane'.", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Fly Future Education', max_length=120)),
                ('tagline', models.CharField(default='Empowering Dreams Through Global Education', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('about_short', models.TextField(blank=True, help_text='A short 2-3 sentence summary used in the footer and social previews.')),
                ('phone_primary', models.CharField(default='+880 1805-030201', max_length=40)),
                ('whatsapp_number', models.CharField(default='8801805030201', help_text='Digits only with country code, no + or spaces (used to build wa.me links).', max_length=40)),
                ('email', models.EmailField(default='flufutureeducation@gmail.com', max_length=254)),
                ('address', models.TextField(default='25/5/A Pragati Sharani, Shahjadpur, Gulshan, Dhaka -1212.')),
                ('office_hours', models.CharField(default='Sat - Thu: 10:00 AM - 7:00 PM | Friday: Closed', max_length=200)),
                ('google_map_embed_url', models.URLField(blank=True, help_text="Paste the 'src' URL from a Google Maps embed iframe for the office address.")),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/flyfutureeducationbd/')),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('messenger_url', models.URLField(blank=True, help_text='Link used by the floating Messenger chat bubble, e.g. https://m.me/flyfutureeducationbd')),
                ('footer_text', models.CharField(default='Fly Future Education — Empowering Dreams Through Global Education.', max_length=200)),
                ('default_meta_title', models.CharField(default='Fly Future Education | Study Abroad Consultants in Dhaka', max_length=70)),
                ('default_meta_description', models.CharField(default='Fly Future Education helps Bangladeshi students study abroad with expert visa processing, university admissions, scholarship and IELTS/PTE guidance.', max_length=160)),
                ('default_og_image', models.ImageField(blank=True, null=True, upload_to='site/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.PositiveIntegerField()),
                ('suffix', models.CharField(blank=True, default='+', max_length=10)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='Overrides the <title> tag. Falls back to the page title if left blank. Aim for under 60 characters.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Search-result snippet. Aim for 120-160 characters.', max_length=160)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, help_text="e.g. 'Now studying at University of Toronto, Canada'", max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('country', models.CharField(blank=True, max_length=80)),
                ('message', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='core.faqcategory')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('cover_note', models.TextField(blank=True)),
                ('resume', models.FileField(upload_to='career_applications/%Y/%m/')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.jobposting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
