# Generated by Django 5.1.15 on 2026-07-25 10:20

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='Overrides the <title> tag. Falls back to the page title if left blank. Aim for under 60 characters.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Search-result snippet. Aim for 120-160 characters.', max_length=160)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('flag_image', models.ImageField(blank=True, null=True, upload_to='destinations/flags/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='destinations/hero/')),
                ('overview', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('why_study_here', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('visa_requirements', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('work_rights', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Post-study work (PSW) rights and work-while-studying information.')),
                ('cost_of_living', models.CharField(blank=True, help_text="e.g. 'BDT 60,000 - 90,000 / month'", max_length=150)),
                ('tuition_range', models.CharField(blank=True, help_text="e.g. 'BDT 6,00,000 - 12,00,000 / year'", max_length=150)),
                ('intake_seasons', models.CharField(blank=True, help_text="e.g. 'February, September'", max_length=150)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured destinations appear on the homepage.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='destinations/universities/')),
                ('ranking', models.CharField(blank=True, help_text="e.g. 'QS World Rank #120'", max_length=100)),
                ('programs_offered', models.TextField(blank=True, help_text='Comma-separated or short free text list.')),
                ('tuition_range', models.CharField(blank=True, max_length=150)),
                ('website_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='destinations.country')),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'ordering': ['order', 'name'],
            },
        ),
    ]
