# Generated by Django 5.1.15 on 2026-07-25 10:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('designation', models.CharField(max_length=150)),
                ('department', models.CharField(choices=[('admissions', 'Admissions'), ('visa', 'Visa Processing'), ('counselling', 'Counselling'), ('test_prep', 'Test Prep'), ('management', 'Management')], default='counselling', max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
