# Generated by Django 5.1.15 on 2026-07-25 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('desired_program', models.CharField(blank=True, choices=[('diploma', 'Diploma'), ('bachelors', "Bachelor's"), ('masters', "Master's"), ('phd', 'PhD'), ('language_course', 'Language Course')], max_length=150)),
                ('preferred_intake', models.CharField(blank=True, help_text="e.g. 'September 2026'", max_length=100)),
                ('message', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, help_text='Resume, transcript, or passport copy (PDF/DOC/DOCX/JPG/PNG).', null=True, upload_to='applications/%Y/%m/')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_progress', 'In Progress'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('staff_notes', models.TextField(blank=True, help_text='Internal notes, not visible to the applicant.')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='destinations.country')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
