from django.test import TestCase
from django.urls import reverse

from .models import FAQ, FAQCategory, SiteSettings, StaticPage


class SiteSettingsSingletonTests(TestCase):
    def test_load_always_returns_same_row(self):
        first = SiteSettings.load()
        second = SiteSettings.load()
        self.assertEqual(first.pk, second.pk)
        self.assertEqual(SiteSettings.objects.count(), 1)

    def test_save_always_uses_pk_one(self):
        obj = SiteSettings(site_name="Should still be singleton")
        obj.save()
        self.assertEqual(obj.pk, 1)
        self.assertEqual(SiteSettings.objects.count(), 1)


class StaticPageSlugTests(TestCase):
    def test_slug_autogenerated_from_title(self):
        page = StaticPage.objects.create(title="Cookie Policy", body="<p>Body</p>")
        self.assertEqual(page.slug, "cookie-policy")

    def test_slug_uniqueness_appends_suffix(self):
        StaticPage.objects.create(title="Cookie Policy", body="<p>1</p>")
        second = StaticPage.objects.create(title="Cookie Policy", body="<p>2</p>")
        self.assertEqual(second.slug, "cookie-policy-2")


class CorePageViewTests(TestCase):
    def test_home_page_loads(self):
        response = self.client.get(reverse("core:home"))
        self.assertEqual(response.status_code, 200)

    def test_about_page_loads(self):
        response = self.client.get(reverse("core:about"))
        self.assertEqual(response.status_code, 200)

    def test_faq_page_lists_only_published_questions(self):
        category = FAQCategory.objects.create(name="Visa")
        FAQ.objects.create(category=category, question="Published?", answer="<p>Yes</p>", is_published=True)
        FAQ.objects.create(category=category, question="Hidden?", answer="<p>No</p>", is_published=False)
        response = self.client.get(reverse("core:faq"))
        self.assertContains(response, "Published?")
        self.assertNotContains(response, "Hidden?")

    def test_privacy_page_returns_404_without_content(self):
        # Without a seeded StaticPage row this should 404 cleanly rather than error.
        response = self.client.get(reverse("core:privacy_policy"))
        self.assertEqual(response.status_code, 404)

    def test_search_view_requires_query(self):
        response = self.client.get(reverse("core:search"))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Type a keyword")


class ErrorAndSEOEndpointTests(TestCase):
    def test_unknown_url_returns_404(self):
        response = self.client.get("/this-page-does-not-exist/")
        self.assertEqual(response.status_code, 404)

    def test_sitemap_and_robots_are_reachable(self):
        self.assertEqual(self.client.get("/sitemap.xml").status_code, 200)
        self.assertEqual(self.client.get("/robots.txt").status_code, 200)
