# Generated by Django 5.1.15 on 2026-07-25 10:20

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='Overrides the <title> tag. Falls back to the page title if left blank. Aim for under 60 characters.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Search-result snippet. Aim for 120-160 characters.', max_length=160)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='scholarships/')),
                ('amount_coverage', models.CharField(help_text="e.g. 'Up to 50% tuition waiver'", max_length=150)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('eligibility', ckeditor_uploader.fields.RichTextUploadingField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('apply_link', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholarships', to='destinations.country')),
            ],
            options={
                'ordering': ['order', 'deadline'],
            },
        ),
    ]
